### ISSUE TITLE
Consolamentum tenet makes young numenoreans, orcs and (in the future) elves commit suicide

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#369]
The Consolamentum faith tenet makes suicide legal so you may choose to pass away when you feel like you're fulfilled.

However, a player has reported that since the AI considers around 60 to be an acceptable age to end it, young AI numenoreans (especially annoying with ones own children) tend to commit suicide around that age too.
Also needs fixing for orcs and elves

**Comment by jj248** [comment]
I believe this was fixed.  Testers to confirm.

**Comment by JukeJukestar** [comment]
Ran a few tests, this appears to be fixed.
A potential issue that could still exist would be that the AI now doesnt use the decision to commit suicide at all, blood of numenor or not. Testing this wasnt really possible though.
