### ISSUE TITLE
Elves grant out human counties to elves and vice versa

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#664]
Elves grant out human/ feudal holdings to elves, who become feudal.
Humans do the opposite with elven holdings.

**Comment by jj248** [comment]
Just brainstorming some thoughts here while waiting for the wee Pichu to get back to sleep...

- ideally I'd find the process which actually manages how the AI gives out these excess titles.
- failing that, I could try using an on action for title gain to check if ai and mismatched holding type to race, then replace with random correct culture and set liege.
- above would solve holding mismatch but not granting of colonies.

**Comment by jj248** [comment]
I've pushed something that hopefully will fix this.  Please test.

**Comment by Commander-Sol** [comment]
> I've pushed something that hopefully will fix this. Please test.

In my testing with the elves today I noticed Galadriel granting human fiefs in Celebrant to elven characters, but it's certainly less prolific than before. Haven't seen any humans getting elven holdings though. Will attempt to replicate tomorrow.

**Comment by Commander-Sol** [comment]
> > I've pushed something that hopefully will fix this. Please test.
> 
> In my testing with the elves today I noticed Galadriel granting human fiefs in Celebrant to elven characters, but it's certainly less prolific than before. Haven't seen any humans getting elven holdings though. Will attempt to replicate tomorrow.

Confirming this happens, Galadriel consistently grants human holdings in Celebrant to elves whenever she takes counties or the duchy as a whole.

**Comment by jj248** [comment]
I've tried pushing another fix for this - hopefully it won't result in Year 1 CTDs.

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/220405439-0021d791-2eef-49f2-ae14-bac39c030e97.png)
I was able to figure out how galadriel has been giving out the titles.

**Comment by savagesach** [comment]
is there no way to disable "grant to local noble" for different races?

**Comment by savagesach** [comment]
nvm I didn't read properly, that just gives the title to local culture. every time I switch from galadriel to observer mode, the ai immediately gives the title to other elves. the only thing I can think of is that there's some ai only interaction

**Comment by jj248** [comment]
I *believe* I fixed this last night: https://github.com/MattTheLegoman/RealmsInExile/commit/3bcfd08df4d61953374b5e8bd5e7a7a6ad4fb1a6

When was your last pull?

**Comment by savagesach** [comment]
idk when my last pull was, but I tested it with a newly reinstalled dev version and it's still a problem
![image](https://user-images.githubusercontent.com/86676697/220462816-35a71343-0dc8-4da6-a85a-ee00750cc0b0.png)

**Comment by VectorMaximus** [comment]
Yep, I similarly just tested this, under the exact same circumstances. Galadriel immediately gave out the counties in Parth Celebrant to Elves.

**Comment by jj248** [comment]
I've pushed an attempted fix that MAY cause CTD instability, so if that starts happening again, it's almost certainly THIS.

**Comment by Jauffr** [comment]
After playing a few elf games and many observer games the past few days. I can confidently say that elves can no longer hand out human counties to other elves. Humans can not hand out elven counties to other humans, though once I had a human vassal conquer an elf county and lost his old one. This meant he was stuck with a county he couldn't use. That is working as intended though and was purely his own fault

**Comment by jj248** [comment]
Agreed.  Serves him right.  Closing.
